config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#top'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  belongs_to :user
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title,:body, presence: true
    has_many :favorites, dependent: :destroy
    
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower_relationships, class_name: "Relationship", foreign_key: "follower_id"
  has_many :followers, through: :follower_relationships, source: :followed
  has_many :followed_Relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :followeds, through: :followed_Relationships, source: :follower

  
  def following?(other_user)
    self.followers.include?(other_user)
  end

  # ユーザーをフォローする
  def follow(other_user)
    unless self == other_user
    self.follower_relationships.create(followed_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    self.follower_relationships.find_by(followed_id: other_user.id).destroy
  end

         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys:[:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render action: :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = User.find(current_user.id)
    @users = @user
  end

  def show
    @book1 = Book.new
    @book = Book.find(params[:id])
    @users = @book.user
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if current_user == @book.user
      @book = Book.find(params[:id])
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if user_signed_in?
      @user = User.find(params[:id])
    else
      flash[:notice] = 'こちらからご登録後に閲覧いただけます！'
      redirect_to new_user_registration_path
    end
  end

  def index
    @user = User.find(current_user.id)
    @users = @user
    @user_all = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @users = @user
    @books = @user.books
    @book = Book.new
  end

  def edit
     @user = User.find(params[:id])
     if current_user == @user
       @user = User.find(params[:id])
     else
       redirect_to user_path(current_user.id)
     end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.save!
    render action: 'new'
    nil
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<br>
<div class="container">
  <div class="row">
    <div class="col-12">
<%= form_with model:@book, local: true do |f| %>
   <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
      </ul>
    </div>
   <% end %>
   
 <div class="field">
   <label for="book_title">Title</label>
   <div><%= f.text_field :title %></div>
 </div>
 <div class="field">
  <label for="book_body">Body</label>
  <div><%= f.text_area :body %></div>
 </div>
 <div class="actions"><%= f.submit 'Update Book' %></div>
<% end %>
<%= link_to "Show", book_path(@book) %>|<%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
    <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul class="aaa">
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <div class="row">


    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @users, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th>
              <%= link_to following_user_path(@user) do %>
              <%= @user.followers.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>followers</th>
            <th>
             <%= link_to followers_user_path(@user) do %>
             <%= @user.followeds.count %>
             <% end %>
            </th>
          </tr>
        </tbody>
      </table>
      <br>
      <div class="row">
        <%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog edit_user_19881' %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <div><label for="book_title">Title</label></div>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <div><label for="book_body">Opinion</label></div>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="form-group"><%= f.submit 'Create Book', class: 'btn btn-success' %></div>
      <% end %>
    </div>




    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
               <%= attachment_image_tag book.user, :profile_image, size: '40x40',  fallback: "no_image.jpg", class: "attachment user profile_image" %>
              <% end %>
              </td>
            <td><%= link_to "#{book.title}", book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td class="book_<%= book.id %>">
             <%= render 'like', book: book %>
            </td>
            <td>コメント数:<%= book.post_comments.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>new</h1>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
    <% if @book1.errors.any? %>
    <h3><%= pluralize(@book1.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul class="aaa">
      <% @book1.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @users, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>

      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @users.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @users.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th>
              <%= link_to following_user_path(@users) do %>
              <%= @users.followers.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>followers</th>
            <th>
              <%= link_to followers_user_path(@users) do %>
              <%= @users.followeds.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <% unless current_user == @users %>
              <% if current_user.following?(@users) %>
                <th>
                  <%= form_for(current_user.follower_relationships.find_by(followed_id: @users.id),html: { method: :delete },remote: true) do |f| %>
                    <%= f.submit "フォロー外す", class: "btn btn-primary" %>
                  <% end %>
                </th>
              <% else %>
                <th>
                  <%= form_for(current_user.follower_relationships.build, remote: true) do |f| %>
                  <%= hidden_field_tag :followed_id, @users.id %>
                  <%= f.submit "フォローする", class: "btn btn-primary" %>
                  <% end %>
                </th>
              <% end %>
            <% end %>
          </tr>
        </tbody>
      </table>
      <br>
      <div class="row">
         <%= link_to "", edit_user_path(@users), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book1, local:true do |f| %>
      <div class="form-group">
        <div><label for="book_title">Title</label></div>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <div><label for="book_body">Opinion</label></div>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="form-group"><%= f.submit 'Create Book', class: 'btn btn-success' %></div>
      <% end %>
    </div>




    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@users) do %>
              <%= attachment_image_tag @users, :profile_image, size: '40x40', fallback: "no_image.jpg" %>
              <div><%= @users.name %></div>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book) do %>
               <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <td class="book_<%= @book.id %>">
            <%= render 'like', book: @book %>
            </td>
            <td>コメント数:<%= @book.post_comments.count %></td>

            <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path, class: 'btn btn-sm btn-success edit_book_16950' %></td>
            <td><%= link_to 'Destroy', book_path(@book), class: 'btn btn-sm btn-danger destroy_book_16950', method: :delete, data:{confirm: "本当に削除しますか？"} %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
        <div class="comments_table">
          <%= render 'post_comments/table', book: @book %>
        </div>

        <div class="new-comment">
          <%= render 'post_comments/form', book: @book, post_comment: @post_comment %>
        </div>
    </div>
  </div>
</div>

app/views/books/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>in <i class="fas fa-book"></i><strong>Bookers</strong>,</p>

      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

<h1>ようこそ Bookers へ！</h1>
<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><%= link_to "start", books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: 'navbar-brand text-white' %>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to " Home", user_path(current_user.id), class: 'nav-link text-light fas fa-home' %>
              </li>
              <li class="nav-item">
                <%= link_to " Users", users_path, class: 'nav-link text-light fas fa-users' %>
              </li>
              <li class="nav-item">
                <%= link_to " Books", books_path, class: 'nav-link text-light fas fa-book-open' %>
              </li>
              <li class="nav-item">
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: 'nav-link text-light fas fa-sign-out-alt' %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to " Home", root_path, class: 'nav-link text-light fas fa-home' %>
              </li>
              <li class="nav-item">
                <%= link_to " About", home_about_path, class: 'nav-link text-light fas fa-link' %>
              </li>
              <li class="nav-item">
                <%= link_to " sign up", new_user_registration_path, class: 'nav-link text-light fas fa-user-plus' %>
              </li>
              <li class="nav-item">
                <%= link_to " login", new_user_session_path, class: 'nav-link text-light fas fa-sign-in-alt' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>    
    <p id="notice"><%= flash[:notice] %></p>
    <% if user_signed_in? %>
      <div class="search-form">
        <div class="container mt-1">
          <div class="row">
            <div class="mx-auto">
              <%= form_tag(search_path, method: :get) do %>
                <%= text_field_tag 'word' %>
                <%= select_tag 'model', options_for_select([['User', '1'], ['Book', '2']]) %>
                <%= select_tag 'search', options_for_select([['完全一致', 'matchs'], ['前方一致', 'forward'], ['後方一致', 'backward'], ['部分一致', 'partical']]) %>
                <%= submit_tag '検索' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>    
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
      <h3><%= @user.errors.count %>error prohibited this obj from<br>
      being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
      <%= form_with model: @user, local:true do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class: 'form-control name' %>
      </div>
      <div class="form-group">
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: 'form-control-file user_image' %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class: 'form-control introduction' %>
      </div>
      <div class="form-group">
        <%= f.submit 'Update User', class: 'btn btn-secondary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/inddex.html.erb
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
    <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul class="aaa">
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <div class="row">


    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @users, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th>
              <%= link_to following_user_path(@user) do %>
              <%= @user.followers.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>followers</th>
            <th>
             <%= link_to followers_user_path(@user) do %>
             <%= @user.followeds.count %>
             <% end %>
            </th>
          </tr>
        </tbody>
      </table>
      <br>
      <div class="row">
        <%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog edit_user_19881' %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <div><label for="book_title">Title</label></div>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <div><label for="book_body">Opinion</label></div>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="form-group"><%= f.submit 'Create Book', class: 'btn btn-success' %></div>
      <% end %>
    </div>




    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user_all.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, size: '40x40', fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followers.count %></td>
            <td>フォロワー数:<%= user.followeds.count %></td>
            <% if current_user == user %>
             <td></td>
            <% end %>
            <% unless current_user == user %>
              <% if current_user.following?(user) %>
                <td>
                  <%= form_for(current_user.follower_relationships.find_by(followed_id: user.id),html: { method: :delete },remote: true) do |f| %>
                    <%= f.submit "フォロー外す", class: "btn" %>
                  <% end %>
                </td>
              <% else %>
                <td>
                  <%= form_for(current_user.follower_relationships.build, remote: true) do |f| %>
                  <%= hidden_field_tag :followed_id, user.id %>
                  <%= f.submit "フォローする", class: "btn" %>
                  <% end %>
                </td>
              <% end %>
            <% end %>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>in <i class="fas fa-book"></i><strong>Bookers</strong>,</p>

      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div id="error_explanation">
    <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul class="aaa">
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>
  </div>

  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @users, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th>
              <%= link_to following_user_path(@user) do %>
              <%= @user.followers.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>followers</th>
            <th>
              <%= link_to followers_user_path(@user) do %>
              <%= @user.followeds.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <% unless current_user == @user %>
              <% if current_user.following?(@user) %>
                <th>
                  <%= form_for(current_user.follower_relationships.find_by(followed_id: @user.id),html: { method: :delete },remote: true) do |f| %>
                    <%= f.submit "フォロー外す", class: "btn btn-primary" %>
                  <% end %>
                </th>
              <% else %>
                <th>
                  <%= form_for(current_user.follower_relationships.build, remote: true) do |f| %>
                  <%= hidden_field_tag :followed_id, @user.id %>
                  <%= f.submit "フォローする", class: "btn btn-primary" %>
                  <% end %>
                </th>
              <% end %>
            <% end %>
          </tr>  
        </tbody>
      </table>
      <br>
      <div class="row">
         <%= link_to "", edit_user_path(@user), class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %>
      </div>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
      <div class="form-group">
        <div><label for="book_title">Title</label></div>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <div><label for="book_body">Opinion</label></div>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="form-group"><%= f.submit 'Create Book', class: 'btn btn-success' %></div>
      <% end %>
    </div>




    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path do %>
              <%= attachment_image_tag @users, :profile_image, size: '40x40',  fallback: "no_image.jpg", class: "attachment user profile_image" %>
              <% end %>
            </td>
            <td><%= link_to "#{book.title}", book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td>コメント数:<%= book.post_comments.count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>